#!/bin/bash
# Author: Aniverse
#
# 2018.12.14
# Ver.1.0.0
#
# apt-get update && apt-get -y install screen unzip && screen -R GG
# bash <(wget --no-check-certificate -qO- https://github.com/Aniverse/A/raw/i/z2)

black=$(tput setaf 0); red=$(tput setaf 1); green=$(tput setaf 2); yellow=$(tput setaf 3);
blue=$(tput setaf 4); magenta=$(tput setaf 5); cyan=$(tput setaf 6); white=$(tput setaf 7);
on_red=$(tput setab 1); on_green=$(tput setab 2); on_yellow=$(tput setab 3); on_blue=$(tput setab 4);
on_magenta=$(tput setab 5); on_cyan=$(tput setab 6); on_white=$(tput setab 7); bold=$(tput bold);
dim=$(tput dim); underline=$(tput smul); reset_underline=$(tput rmul); standout=$(tput smso);
reset_standout=$(tput rmso); normal=$(tput sgr0); alert=${white}${on_red}; title=${standout};
baihuangse=${white}${on_yellow}; bailanse=${white}${on_blue}; bailvse=${white}${on_green};
baiqingse=${white}${on_cyan}; baihongse=${white}${on_red}; baizise=${white}${on_magenta};
heibaise=${black}${on_white}; heihuangse=${on_yellow}${black}
jiacu=${normal}${bold}
shanshuo=$(tput blink); wuguangbiao=$(tput civis); guangbiao=$(tput cnorm)
CW="${bold}${baihongse} ERROR ${jiacu}";ZY="${baihongse}${bold} ATTENTION ${jiacu}";JG="${baihongse}${bold} WARNING ${jiacu}"

# [[ ! $(command -v unzip) ]] && apt-get install -y unzip
# echo -e "${bold}${yellow}Who's your daddy?${normal}" ; read -t 5 -e zippass

zippass=$1

cd ; wget -q https://github.com/Aniverse/swis/raw/master/rUD8YAIm4ip8WZ1z -O rUD8YAIm4ip8WZ1z
unzip -qq -o -P $zippass rUD8YAIm4ip8WZ1z 2>/dev/null || { echo -e "\n${bold}${baihongse}What's wrong with you?${normal}\n" ; rm -f rUD8YAIm4ip8WZ1z ; exit 1 ; }

echo -e "${bold}${yellow}Go!Go!Go!${normal}"

# SWAP 防止内存不足
dd if=/dev/zero of=/root/.swapfile bs=1M count=2048
mkswap /root/.swapfile
swapon /root/.swapfile
swapon -s
echo -e "\n$(tput setaf 7)$(tput setab 1) DONE $(tput sgr0)\n"

# 设置简单的密码，登陆 SFTP 把文件下回来用
# 反正不是我自己平常用的密码，公开出来无所谓，这 VPS 编译完直接就删掉的东西……
echo -ne 'inexistence233\ninexistence233\n' | passwd root
echo -e "\n$(tput setaf 7)$(tput setab 1) DONE $(tput sgr0)\n"

# 开启 SSH root 密码登陆，安全性放弃治疗的
sed -i '/.*AllowGroups.*/d' /etc/ssh/sshd_config
sed -i '/.*PasswordAuthentication.*/d' /etc/ssh/sshd_config
sed -i '/.*PermitRootLogin.*/d' /etc/ssh/sshd_config
echo 'PermitRootLogin yes' >> /etc/ssh/sshd_config
/etc/init.d/ssh restart
echo -e "\n------ DONE  ------\n"

# 文件存放到这个路径
mkdir -p /root/0.file/library

echo -e "\n\n\n$(tput setaf 7)$(tput setab 1)------ DONE  ------$(tput sgr0)\n\n\n"

#########################################################################################################

# 设定参数
export ARCH=amd64
export CODENAME=$(cat /etc/os-release | grep VERSION= | tr '[A-Z]' '[a-z]' | sed 's/\"\|(\|)\|[0-9.,]\|version\|lts//g' | awk '{print $2}')
export DATE=$(date +%Y%m%d)
export version=1.1.11.111

# 编译部分，正文
function install_lt() {

apt-get -y install lrzsz sudo screen nano tree build-essential pkg-config autoconf automake libtool git checkinstall libboost-dev libboost-system-dev libboost-chrono-dev libboost-random-dev libssl-dev geoip-database libgeoip-dev libboost-python-dev libgl1-mesa-dev zlib1g-dev

git clone --depth=1 -b $branch https://github.com/Aniverse/libtorrent libtorrent-$version
cd libtorrent-$version
mkdir -p doc-pak ; echo "an efficient feature complete C++ bittorrent implementation, modified for higher performance" >description-pak

mv -f ../eBt3D4t0mLZ3464 src/settings_pack.cpp

./autotool.sh
./configure --enable-python-binding --with-libiconv --disable-debug --enable-encryption --with-libgeoip=system CXXFLAGS=-std=c++11
make -j$(nproc)
checkinstall -y --pkgname=libtorrent-rasterbar --pkggroup libtorrent --pkgversion $version
mv libtorrent-rasterbar*deb /root/0.file/libtorrent-rasterbar.mod.${version}.${CODENAME}.${ARCH}.deb

tar zcvpf /root/0.file/libtorrent-rasterbar.mod.${version}.${CODENAME}.${ARCH}.tar.gz /root/libtorrent-$version
ldconfig ; }

time install_lt ; echo
python -c "import libtorrent ; print libtorrent.version"
pkg-config --exists --print-errors "libtorrent-rasterbar >= 3.0.0" 2>&1 | awk '{print $NF}' | grep -oE [0-9.]+
echo -e "\n\n\n$(tput setaf 7)$(tput setab 1)------ LT DONE ------$(tput sgr0)\n\n\n"
